- name: Sample Expense Project
  hosts: all
  become: true
  tasks:
    - name: Install NGINX
      ansible.builtin.yum:
        name: nginx
        state: installed

    - name: Copy NGINX Config
      ansible.builtin.copy:
        src: nginx.conf
        dest: /etc/nginx/default.d/expense.conf

    - name: Remove Old content
      ansible.builtin.file:
        path: /usr/share/nginx/html/*
        state: absent

    - name: Create App Directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: Download the frontend content
      ansible.builtin.unarchive:
        src: /tmp/frontend.zip https://expense-artifacts.s3.amazonaws.com/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: Start NGINX service
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: yes